---
title: "___"
author: "Pierre Vandenberghe, Théo Galand, Arthur Ohmann, Jérôme Borgniet"
format:
  pdf:
    documentclass: report
    toc: true
editor: visual
lang: fr
bibliography: references.bib
---

<!--# Un rapport est différent d'un carnet de notes. Il ne s'agit donc pas de faire du copier-coller d'un document vers l'autre. Un rapport de synthèse doit être compréhensible sans devoir lire le carnet de notes. Le rapport de synthèse doit être  rédigé avec un style et une présentation adéquats. -->

## Introduction

<!--% Rédigez l'introduction de ce rapport en 5-6 phrases.-->

La différenciation taxonomique des fourmis (Formicidae) repose largement sur l'analyse de traits morphologiques mesurables et de leurs variations. Ces relations biométriques entre les différents segments corporels constituent une base essentielle pour la classification des espèces.

Le jeu de données analysé ici rassemble les mesures morphométriques précises de 339 espèces, échantillonnées au travers de trois environnements distincts. Cette approche permet de confronter la variabilité phénotypique interspécifique aux contraintes écologiques imposées par le milieu de vie.

<!--% Rédigez le but de ce rapport en 2 phrases.-->
 
## But 
 
Le but de ce rapport est d'identifier les facteurs influençant la morphologie des différentes fourmis et de présenter les deux modèles que nous pensons les plus pertinents de notre bloc-notes pour justifier cela. Nous avons utilisé les données récoltées par Bishop T. et Ewers R.

## Matériel et méthodes

<!--% Cette section doit comprendre deux parties. La première partie doit expliciter les données employées et la seconde traiter des analyses réalisées et des logiciels employés.-->

Les données ont été trouvées sur le site : <https://zenodo.org.> Les données ont été remaniées et modifiées dans le dossier import.R. Nous avons essentiellement utilisés les données liées à la morphométrie par rapport aux différents environnements. Nous réalisons l'analyse avec le logiciel R (r R.version.string) et en particulier le package {modelit} version r packageVersion("modelit") dans la SciViews Box 2025. Saturn Cloud (Linux Ubuntu 22.04) est utilisé pour exécuter le code et compiler la version finale de ce rapport.

## Résultats

<!--% Présentez les deux modèles les plus pertinents que vous avez sélectionnés. Structurez la section en deux parties avec deux titres de niveau trois.-->

### Modèle 1

### Modèle 2

## Discussion et Conclusion

<!--% En tenant compte du but de votre carnet de notes et de vos résultats, discutez de résultats et proposez des conclusions à votre analyse en 5 à 10 phrases. -->

## Bibliographie
